function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_fixed_fit_projection", { near = -1, far = 1 })
	math.randomseed(0)
	timer.delay(2, true, spawn_coin)
end

function spawn_coin()
	local position = go.get_position()
	position.x = math.random(300, 1900)
	-- local hamburger = factory.create("#logofactory", vmath.vector3 (position.x, 750, 0))
	factory.create("#factory", vmath.vector3(math.random(1200, 1900), 750, 0))
end

