local points = 0

function init(self)
	set_text(" ")
	set_points(points)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("deleted") then
		set_text("dead")
	end

	if message_id == hash("add_score") then
		points = points + 1
		set_points(points)
	end
end

function set_text(x)
	text = x 
	gui.set_text(gui.get_node("text"), text)
end

function set_points(x)
	count = "Points: " .. x 
	gui.set_text(gui.get_node("points"), count)

end

