function init(self)
	math.randomseed(0)
end

function spawn_obstacle()
	local position = go.get_position()
	position.x = sys.get_config("display.width")
	position.y = math.random(0, 100)

	local number = math.random()

	if number < 0.25 then
		factory_name = "#obstacle3"
	elseif number < 0.5 then
		factory_name = "#obstacle2"
	else 
		factory_name = "#obstacle1"
	end
	factory.create(factory_name, position)
end

